### ISSUE TITLE
can not opan app after some days

### ISSUE THREAD

**Issue by thawri1** [crashinvaders/gdx-texture-packer-gui#100]
I using the 4.10 version without problem but after some days it does not open.
I also install 4.8.2 and 4.9 versions but have the same issue.

Version: 4.8.2
OS: Mac OS X 10.16 x86_64
JRE: 1.8.0_281 Oracle Corporation
External log file: /Users/hadi/.gdxtexturepackergui/logs/2103130431.log
com.badlogic.gdx.utils.GdxRuntimeException: Unable to invoke method: init of type: com.crashinvaders.texturepackergui.controllers.extensionmodules.ExtensionModuleRepositoryService@9339632 with parameters: []
	at com.github.czyzby.autumn.context.impl.method.MethodInvocation.invoke(MethodInvocation.java:50)
	at com.github.czyzby.autumn.processor.impl.InitiateAnnotationProcessor.doAfterScanning(InitiateAnnotationProcessor.java:42)
	at com.github.czyzby.autumn.context.ContextInitializer.invokeProcessorActionsAfterInitiation(ContextInitializer.java:351)
	at com.github.czyzby.autumn.context.ContextInitializer.initiate(ContextInitializer.java:294)
	at com.crashinvaders.texturepackergui.App.initiateContext(App.java:100)
	at com.crashinvaders.texturepackergui.App.create(App.java:85)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.create(LwjglCanvas.java:210)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$1$1.run(LwjglCanvas.java:96)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.badlogic.gdx.utils.reflect.ReflectionException: Exception occurred in method: init
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:114)
	at com.github.czyzby.kiwi.util.gdx.reflection.Reflection.invokeMethod(Reflection.java:130)
	at com.github.czyzby.autumn.context.impl.method.MethodInvocation.invoke(MethodInvocation.java:47)
	... 21 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:108)
	... 23 more
Caused by: java.lang.NullPointerException
	at com.crashinvaders.texturepackergui.controllers.extensionmodules.ExtensionModuleRepositoryService.init(ExtensionModuleRepositoryService.java:48)
	... 28 more

**Comment by thawri1** [comment]
I also test the jar file but not open.
another jar files like Hiero open without any issue.

**Comment by thawri1** [comment]
I tested multiple versions and  4.3.2 is working.

**Comment by metaphore** [comment]
Sorry for the slow response.

I'm not entirely sure how it's happened, but it has all the symptoms that one of the internal configuration files has got malformed.
For a quick fix I'd just delete this problematic file - `~/.gdxtexturepackergui/modules/repo_cache.json` and it should be fine. 

Please let me know if that helps and if the same problem occurs again.

**Comment by thawri1** [comment]
thanks, the problem solved by deleting this file.
but this file was empty.
