### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by apet2929** [crashinvaders/gdx-texture-packer-gui#106]
I was modifying the output directory (i didnt want to output to the default directory), I pressed backspace and it crashed. I did not have any files in the pack yet, this was the only thing I had done on the pack. This has happened multiple times, with and without images in the pack. 
Version: 4.10.0
OS: Windows 10 10.0 x86
JRE: 1.8.0_251 Oracle Corporation
GPU: GeForce RTX 3060/PCIe/SSE2
OpenGL vendor: NVIDIA Corporation
OpenGL version: 4.6.0 NVIDIA 461.72
[ExtensionModuleRepositoryService] Cached data was loaded
[ConfigurationController] Incremental fonts are disabled
[VisUI] Warning, using invalid libGDX version for VisUI 1.4.8.
You are using libGDX 1.9.11 but you need 1.9.12. This may cause unexpected problems and runtime exceptions.
[GlobalShortcutHandler] Parsing shortcut file: hotkeys_default.txt
java.lang.IllegalArgumentException: actor cannot be null.
	at com.badlogic.gdx.scenes.scene2d.ui.Table.getCell(Table.java:417)
	at com.kotcrab.vis.ui.widget.MenuItem.getImageCell(MenuItem.java:352)
	at com.kotcrab.vis.ui.widget.file.internal.AbstractSuggestionPopup.createMenuItem(AbstractSuggestionPopup.java:36)
	at com.kotcrab.vis.ui.widget.file.internal.DirsSuggestionPopup$1$1.run(DirsSuggestionPopup.java:88)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:157)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.start(ApplicationStarter.java:56)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:35)

**Comment by metaphore** [comment]
Sorry for the late replay.

I believe that the same old bug that was fixed in #98 
Please feel free to reopen if you think the crash is about something else.
