### ISSUE TITLE
Application crashing

### ISSUE THREAD

**Issue by shabman** [crashinvaders/gdx-texture-packer-gui#109]
There's no crash log for this but every time I attempt to change the directory the software crashes and closes. I am not sure if it's an issue or I am doing something wrong.

**Comment by shabman** [comment]
when I try and change the output directory property, the application closes

**Comment by shabman** [comment]
I also get this error if I try to pack my images

[text-red]Exception occurred:[] The atlas output dir (/Users/mustafamalik/Documents/Space Shooter/android/assets) is matching to one of the input files/dirs (/Users/mustafamalik/Documents/Space Shooter/android/assets/darkPurpleStarscape.png). That might lead to an accidental source image loss. Please use separate output directory to write your atlases.
[text-red]Stack trace:[] 
java.lang.IllegalStateException: The atlas output dir (/Users/mustafamalik/Documents/Space Shooter/android/assets) is matching to one of the input files/dirs (/Users/mustafamalik/Documents/Space Shooter/android/assets/darkPurpleStarscape.png). That might lead to an accidental source image loss. Please use separate output directory to write your atlases.
	at com.crashinvaders.texturepackergui.controllers.packing.processors.DataValidationProcessor.processPackage(DataValidationProcessor.java:47)
	at com.crashinvaders.texturepackergui.utils.packprocessing.CompositePackProcessor.processPackage(CompositePackProcessor.java:20)
	at com.crashinvaders.texturepackergui.utils.packprocessing.PackProcessingManager.lambda$execute$0(PackProcessingManager.java:60)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
