### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by ArcaneSunku** [crashinvaders/gdx-texture-packer-gui#115]
Version: 4.10.0
OS: Windows 10 10.0 amd64
JRE: 1.8.0_281 Oracle Corporation
GPU: Radeon RX 580 Series
OpenGL vendor: ATI Technologies Inc.
OpenGL version: 4.6.14739 Compatibility Profile Context 21.6.1 27.20.22001.14011
[ExtensionModuleRepositoryService] Cached data was loaded
[ConfigurationController] Incremental fonts are disabled
[VisUI] Warning, using invalid libGDX version for VisUI 1.4.8.
You are using libGDX 1.9.11 but you need 1.9.12. This may cause unexpected problems and runtime exceptions.
[GlobalShortcutHandler] Parsing shortcut file: hotkeys_default.txt
[text-red]Exception occurred:[] The atlas output dir (C:/Coding Workspace/Projects/GoldenTimes/core/assets/assets/textures) is matching to one of the input files/dirs (C:/Coding Workspace/Projects/GoldenTimes/core/assets/assets/textures/badlogic.jpg). That might lead to an accidental source image loss. Please use separate output directory to write your atlases.
[text-red]Stack trace:[] 
java.lang.IllegalStateException: The atlas output dir (C:/Coding Workspace/Projects/GoldenTimes/core/assets/assets/textures) is matching to one of the input files/dirs (C:/Coding Workspace/Projects/GoldenTimes/core/assets/assets/textures/badlogic.jpg). That might lead to an accidental source image loss. Please use separate output directory to write your atlases.
	at com.crashinvaders.texturepackergui.controllers.packing.processors.DataValidationProcessor.processPackage(DataValidationProcessor.java:47)
	at com.crashinvaders.texturepackergui.utils.packprocessing.CompositePackProcessor.processPackage(CompositePackProcessor.java:20)
	at com.crashinvaders.texturepackergui.utils.packprocessing.PackProcessingManager.lambda$execute$0(PackProcessingManager.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Packing is started
Packing.........
Writing 512x512: C:\Coding Workspace\Projects\GoldenTimes\core\assets\assets\textures\atlas\game.png
Packing is done
Total pack files size is 86833 bytes
1 pages
Total processing time: 0.31sec

java.lang.RuntimeException: Actor: game.
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
	at com.badlogic.gdx.scenes.scene2d.Stage.keyTyped(Stage.java:446)
	at com.crashinvaders.common.PrioritizedInputMultiplexer$Wrapper.keyTyped(PrioritizedInputMultiplexer.java:128)
	at com.crashinvaders.common.PrioritizedInputMultiplexer.keyTyped(PrioritizedInputMultiplexer.java:65)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:81)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:187)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:394)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:141)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.start(ApplicationStarter.java:56)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:35)
Caused by: java.lang.RuntimeException: Actor: game.
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
	at com.kotcrab.vis.ui.widget.VisTextField.changeText(VisTextField.java:702)
	at com.kotcrab.vis.ui.widget.VisTextField$TextFieldClickListener.keyTyped(VisTextField.java:1232)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:57)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
	... 11 more
Caused by: java.lang.IllegalArgumentException: actor cannot be null.
	at com.badlogic.gdx.scenes.scene2d.ui.Table.getCell(Table.java:417)
	at com.kotcrab.vis.ui.widget.MenuItem.getImageCell(MenuItem.java:352)
	at com.kotcrab.vis.ui.widget.file.internal.AbstractSuggestionPopup.createMenuItem(AbstractSuggestionPopup.java:36)
	at com.kotcrab.vis.ui.widget.file.internal.FileSuggestionPopup.createSuggestions(FileSuggestionPopup.java:76)
	at com.kotcrab.vis.ui.widget.file.internal.FileSuggestionPopup.pathFieldKeyTyped(FileSuggestionPopup.java:41)
	at com.kotcrab.vis.ui.widget.file.FileChooser$16.changed(FileChooser.java:558)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
	... 16 more

**Comment by metaphore** [comment]
It appears to be the same bug as with the #112 (typing something in the file chooser crashes the app).
It's fixed by now. If that was actually about something else, please feel free to provide details and reopen.
