### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by mcoswel** [crashinvaders/gdx-texture-packer-gui#121]
> Please paste the crash log in here (already in your clipboard) and, if possible, provide any information that may help to reproduce the issue.

When i try to save my project it crashed.

<details><summary>Application Log</summary>

```
Version: 4.10.1
OS: Windows 7 6.1 amd64
JRE: 13.0.2 Oracle Corporation
GPU: Intel(R) HD Graphics 530
OpenGL vendor: Intel
OpenGL version: 4.4.0 - Build 21.20.16.5064
[ExtensionModuleRepositoryService] Cached data was loaded
[ConfigurationController] Incremental fonts are disabled
[GlobalShortcutHandler] Parsing shortcut file: hotkeys_default.txt
[SystemUtils] Recognized system configuration is Windows (x64)
java.lang.RuntimeException: Actor: miFileSave
|  Image: custom/ic-save
|  Label: Save
|  VisLabel: Ctrl+S
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:125)
	at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:93)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.crashinvaders.common.PrioritizedInputMultiplexer$Wrapper.touchUp(PrioritizedInputMultiplexer.java:136)
	at com.crashinvaders.common.PrioritizedInputMultiplexer.touchUp(PrioritizedInputMultiplexer.java:83)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:394)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.start(ApplicationStarter.java:57)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:35)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unable to invoke method: com.badlogic.gdx.utils.reflect.Method@304a9d7b of object: com.crashinvaders.texturepackergui.controllers.GlobalActions@6bfdb014
	at com.github.czyzby.lml.parser.impl.action.MethodActorConsumer.consume(MethodActorConsumer.java:41)
	at com.github.czyzby.lml.parser.impl.attribute.OnChangeLmlAttribute$1.changed(OnChangeLmlAttribute.java:29)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
	... 15 more
Caused by: com.badlogic.gdx.utils.reflect.ReflectionException: Exception occurred in method: saveProject
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:114)
	at com.github.czyzby.kiwi.util.gdx.reflection.Reflection.invokeMethod(Reflection.java:130)
	at com.github.czyzby.lml.parser.impl.action.MethodActorConsumer.consume(MethodActorConsumer.java:38)
	... 18 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:108)
	... 20 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.String.substring(String.java:1876)
	at com.crashinvaders.texturepackergui.utils.PathUtils.relativize(PathUtils.java:96)
	at com.crashinvaders.texturepackergui.controllers.projectserializer.ProjectSerializer.serializePack(ProjectSerializer.java:127)
	at com.crashinvaders.texturepackergui.controllers.projectserializer.ProjectSerializer.serializeProject(ProjectSerializer.java:94)
	at com.crashinvaders.texturepackergui.controllers.projectserializer.ProjectSerializer.saveProject(ProjectSerializer.java:52)
	at com.crashinvaders.texturepackergui.controllers.GlobalActions.saveProject(GlobalActions.java:222)
	... 25 more
```
</details>

**Comment by metaphore** [comment]
Thanks for submission and sorry for the late reply.

It looks like something unusual has happened to the input file path.
By chance do you still have the project file that causes this crash?

**Comment by metaphore** [comment]
I'm gonna close this one due to very little details to investigate on. Feel free to reopen if the problem still stands.
