### ISSUE TITLE
Crash report - the application won't open

### ISSUE THREAD

**Issue by telekinetic1** [crashinvaders/gdx-texture-packer-gui#128]
<details><summary>Application Log</summary>

```
Version: 4.10.2
OS: Windows 10 10.0 amd64
JRE: 17.0.2 Oracle Corporation
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx64.dll' for target: Windows 10, 64-bit
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:126)
	at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:31)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3NativesLoader.load(Lwjgl3NativesLoader.java:28)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:80)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:91)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.start(ApplicationStarter.java:57)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:35)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: java.lang.UnsatisfiedLinkError: C:\Users\?L?FE\AppData\Local\Temp\libgdx?L?FE\e1cd32f8\gdx64.dll: Can't find dependent libraries
	at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:322)
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:122)
	... 6 more
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\?L?FE\AppData\Local\Temp\libgdx?L?FE\e1cd32f8\gdx64.dll: Can't find dependent libraries
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:328)
	at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:297)
	... 7 more
```
</details>

**Comment by metaphore** [comment]
Hi there!
I understand you had something wrong on your end, but in case others can run into the same case, could you please share what was the problem?

**Comment by Frosty-J** [comment]
Related: https://github.com/libgdx/libgdx/issues/5524
