### ISSUE TITLE
Crashing upon multipage pack copy 

### ISSUE THREAD

**Issue by Rubonnek** [crashinvaders/gdx-texture-packer-gui#130]
After packing a multipage atlas, attempting to copy the pack with Ctrl-Shift-C will crash the UI. 

Tested by packing all the images in [PNGs.zip](https://github.com/crashinvaders/gdx-texture-packer-gui/files/8886319/PNGs.zip)

> Please paste the crash log in here (already in your clipboard) and, if possible, provide any information that may help to reproduce the issue.

```
java.lang.RuntimeException: Actor: VisTextButton: Ok
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:125)
        at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:93)
        at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
        at com.crashinvaders.common.PrioritizedInputMultiplexer$Wrapper.touchUp(PrioritizedInputMultiplexer.java:136)
        at com.crashinvaders.common.PrioritizedInputMultiplexer.touchUp(PrioritizedInputMultiplexer.java:83)
        at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
        at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:394)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
        at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.start(ApplicationStarter.java:57)
        at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:35)
Caused by: java.lang.NullPointerException
        at com.crashinvaders.texturepackergui.controllers.CommonDialogs$5.run(CommonDialogs.java:134)
        at com.crashinvaders.texturepackergui.controllers.CommonDialogs$8.changed(CommonDialogs.java:173)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
        ... 15 more
X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  2 (X_ChangeWindowAttributes)
  Serial number of failed request:  79
  Current serial number in output stream:  80
```

**Comment by metaphore** [comment]
Nicely spotted, thanks! Was a quick fix.

**Comment by Rubonnek** [comment]
Thank you!
