### ISSUE TITLE
Error loading existing project

### ISSUE THREAD

**Issue by Vrekt** [crashinvaders/gdx-texture-packer-gui#141]
I have an existing tpproj file. Its a few months old. Upon trying to open it again I get the error below. I've tried using older and newer versions of texture packer but it still doesn't work. Did my project somehow get corrupted and is there a way I can fix it? I've posted the zipped project file.

```
[text-red]String index out of range: -1[]
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.crashinvaders.texturepackergui.controllers.projectserializer.InputFileSerializer.read(InputFileSerializer.java:83)
	at com.crashinvaders.texturepackergui.controllers.projectserializer.InputFileSerializer.read(InputFileSerializer.java:12)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:1006)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:1102)
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:840)
	at com.crashinvaders.texturepackergui.controllers.projectserializer.ProjectSerializer.deserializePack(ProjectSerializer.java:328)
	at com.crashinvaders.texturepackergui.controllers.projectserializer.ProjectSerializer.deserializeProject(ProjectSerializer.java:200)
	at com.crashinvaders.texturepackergui.controllers.projectserializer.ProjectSerializer.loadProject(ProjectSerializer.java:72)
	at com.crashinvaders.texturepackergui.controllers.GlobalActions.loadProject(GlobalActions.java:191)
	at com.crashinvaders.texturepackergui.controllers.FileDragDropController.handleFileDrop(FileDragDropController.java:108)
	at com.crashinvaders.texturepackergui.DragDropManager.handleFileDrop(DragDropManager.java:23)
	at com.crashinvaders.texturepackergui.desktop.Lwjgl3AppWrapper.lambda$create$0(Lwjgl3AppWrapper.java:111)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:208)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.start(ApplicationStarter.java:62)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:35)
```

[PackerAssets.zip](https://github.com/crashinvaders/gdx-texture-packer-gui/files/10709991/PackerAssets.zip)

**Comment by metaphore** [comment]
I have no issues opening your file with [4.11.0](https://github.com/crashinvaders/gdx-texture-packer-gui/releases/tag/4.11.0).

The error might be somehow related to your file system path. The texture packer save file is a plain text document, you can open it and inspect the input files' path values. Note that all the paths are relative and I see a lot of "../../" in there, which means that you store your project file separately from the source images, which is not a good practice. Another thing worth checking is if you have spaces or non-Latin letters in the parent directories of the images, which might cause weird errors sometimes. If that's the case, it's worth trying to move the images and the project file outside those dirs. But keep in mind that the relative location of the project file to the source images should be preserved, otherwise the relative paths won't be adequately resolved.

**Comment by Vrekt** [comment]
> I have no issues opening your file with [4.11.0](https://github.com/crashinvaders/gdx-texture-packer-gui/releases/tag/4.11.0).
> 
> The error might be somehow related to your file system path. The texture packer save file is a plain text document, you can open it and inspect the input files' path values. Note that all the paths are relative and I see a lot of "../../" in there, which means that you store your project file separately from the source images, which is not a good practice. Another thing worth checking is if you have spaces or non-Latin letters in the parent directories of the images, which might cause weird errors sometimes. If that's the case, it's worth trying to move the images and the project file outside those dirs. But keep in mind that the relative location of the project file to the source images should be preserved, otherwise the relative paths won't be adequately resolved.

Ok so I linked all the images to the source directory and that fixed it. It's odd that it worked before but not now. I did not know it was not good practice so thank you.
