### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by basit112** [crashinvaders/gdx-texture-packer-gui#142]
Version: 4.11.0
OS: Windows 10 10.0 amd64
JRE: 17.0.2 Oracle Corporation
[LWJGL] GLFW_API_UNAVAILABLE error
	Description : WGL: The driver does not appear to support OpenGL
	Stacktrace  :
		org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2024)
		org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2197)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:524)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:462)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:448)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:162)
		com.crashinvaders.texturepackergui.desktop.ApplicationStarter.start(ApplicationStarter.java:62)
		com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:35)
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't create window
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:527)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:462)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:448)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:162)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.start(ApplicationStarter.java:62)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:35)

**Comment by metaphore** [comment]
Hi and thanks for the report!

The error in on the surface:
> The driver does not appear to support OpenGL

Do you have a dedicated GPU or video driver installed for your CPU?

**Comment by metaphore** [comment]
Close for long inactivity.
Feel free to reopen if you provide any further details.
