### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by XxXPornhubXxX** [crashinvaders/gdx-texture-packer-gui#149]
<details><summary>Application Log</summary>

```
Version: 4.13.0
OS: Windows 10 10.0 amd64
JRE: 1.8.0_391 Oracle Corporation
[LWJGL] GLFW_API_UNAVAILABLE error
	Description : WGL: The driver does not appear to support OpenGL
	Stacktrace  :
		org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2058)
		org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2229)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:526)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:462)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:448)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:162)
		com.crashinvaders.texturepackergui.desktop.ApplicationStarter.startGuiApp(ApplicationStarter.java:162)
		com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:75)
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't create window
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:529)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:462)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:448)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:162)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.startGuiApp(ApplicationStarter.java:162)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:75)
```
</details>

**Comment by Frosty-J** [comment]
Outstanding name - just the inconspicuous sort of stuff I like to see at the top of my emails.

Do you have proper graphics drivers and do other OpenGL things work such as new libGDX projects with the LWJGL3 backend, or LWJGL(2) failing that?
