### ISSUE TITLE
 Input file does not exist: C:\Users\Me\Downloads\gdx-texturepacker-4.4.0

### ISSUE THREAD

**Issue by adfaure** [crashinvaders/gdx-texture-packer-gui#22]
Hello, I am getting this issue when I try to pack the project.
Thanks for the help :)

```
Packing is started
[output-red]Exception occurred:[] Input file does not exist: C:\Users\Me\Downloads\gdx-texturepacker-4.4.0
[output-red]Stack trace:[] 
java.lang.IllegalArgumentException: Input file does not exist: C:\Users\Me\Downloads\gdx-texturepacker-4.4.0
	at com.badlogic.gdx.tools.FileProcessor.process(FileProcessor.java:117)
	at com.crashinvaders.texturepackergui.controllers.packing.processors.PackingProcessor.deleteOldFiles(PackingProcessor.java:134)
	at com.crashinvaders.texturepackergui.controllers.packing.processors.PackingProcessor.performPacking(PackingProcessor.java:44)
	at com.crashinvaders.texturepackergui.controllers.packing.processors.PackingProcessor.processPackage(PackingProcessor.java:31)
	at com.crashinvaders.texturepackergui.utils.packprocessing.CompositePackProcessor.processPackage(CompositePackProcessor.java:20)
	at com.crashinvaders.texturepackergui.utils.packprocessing.PackProcessingManager$1.run(PackProcessingManager.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by adfaure** [comment]
I found the problem, I needed to fill the output directory :)
I guess I can close the issue unless you want to add a warning instead of crashing.

**Comment by metaphore** [comment]
Yeah, and since you're not the first one get confused with that, it looks like a problem now.
Let's keep this open until I figure something up.
