### ISSUE TITLE
Cant run the program, it just opens a gray window.

### ISSUE THREAD

**Issue by rogerlopz** [crashinvaders/gdx-texture-packer-gui#30]
Hi, i have been using this software for quite some time now and this is the first time it happens to me.

I have downloaded versions `4.4.0` and `4.5.0` and both open just a gray screen:
![gray display gdx](https://user-images.githubusercontent.com/4995589/32418127-5402bd10-c221-11e7-9602-2932b966279c.png)

It doesnt matter how i open it (.exe .jar .bat...),

My system info:
Windows 10 64 bits
Running this command `java -XshowSettings:properties -version` gave me this:
```
Property settings:
    awt.toolkit = sun.awt.windows.WToolkit
    file.encoding = Cp1252
    file.encoding.pkg = sun.io
    file.separator = \
    java.awt.graphicsenv = sun.awt.Win32GraphicsEnvironment
    java.awt.printerjob = sun.awt.windows.WPrinterJob
    java.class.path = .
    java.class.version = 52.0
    java.endorsed.dirs = C:\Program Files\Java\jre1.8.0_151\lib\endorsed
    java.ext.dirs = C:\Program Files\Java\jre1.8.0_151\lib\ext
        C:\WINDOWS\Sun\Java\lib\ext
    java.home = C:\Program Files\Java\jre1.8.0_151
    java.io.tmpdir = C:\Users\Roger\AppData\Local\Temp\
    java.library.path = C:\ProgramData\Oracle\Java\javapath
        C:\WINDOWS\Sun\Java\bin
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\ProgramData\Oracle\Java\javapath
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\WINDOWS\System32\Wbem
        C:\WINDOWS\System32\WindowsPowerShell\v1.0\
        C:\Program Files\nodejs\
        C:\Program Files\Git\cmd
        C:\Program Files\PuTTY\
        C:\Program Files\Java\jdk1.8.0_144\bin

        C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86
        C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64
        C:\Users\Roger\AppData\Local\Microsoft\WindowsApps

        C:\Program Files\Microsoft VS Code\bin
        C:\Users\Roger\AppData\Roaming\npm
        .
    java.runtime.name = Java(TM) SE Runtime Environment
    java.runtime.version = 1.8.0_151-b12
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 1.8
    java.vendor = Oracle Corporation
    java.vendor.url = http://java.oracle.com/
    java.vendor.url.bug = http://bugreport.sun.com/bugreport/
    java.version = 1.8.0_151
    java.vm.info = mixed mode
    java.vm.name = Java HotSpot(TM) 64-Bit Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 1.8
    java.vm.vendor = Oracle Corporation
    java.vm.version = 25.151-b12
    line.separator = \r \n
    os.arch = amd64
    os.name = Windows 10
    os.version = 10.0
    path.separator = ;
    sun.arch.data.model = 64
    sun.boot.class.path = C:\Program Files\Java\jre1.8.0_151\lib\resources.jar
        C:\Program Files\Java\jre1.8.0_151\lib\rt.jar
        C:\Program Files\Java\jre1.8.0_151\lib\sunrsasign.jar
        C:\Program Files\Java\jre1.8.0_151\lib\jsse.jar
        C:\Program Files\Java\jre1.8.0_151\lib\jce.jar
        C:\Program Files\Java\jre1.8.0_151\lib\charsets.jar
        C:\Program Files\Java\jre1.8.0_151\lib\jfr.jar
        C:\Program Files\Java\jre1.8.0_151\classes
    sun.boot.library.path = C:\Program Files\Java\jre1.8.0_151\bin
    sun.cpu.endian = little
    sun.cpu.isalist = amd64
    sun.desktop = windows
    sun.io.unicode.encoding = UnicodeLittle
    sun.java.launcher = SUN_STANDARD
    sun.jnu.encoding = Cp1252
    sun.management.compiler = HotSpot 64-Bit Tiered Compilers
    sun.os.patch.level =
    sun.stderr.encoding = cp850
    sun.stdout.encoding = cp850
    user.country = MX
    user.dir = C:\Users\Roger
    user.home = C:\Users\Roger
    user.language = es
    user.name = Roger
    user.script =
    user.timezone =
    user.variant =

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

I dont know if im doing something wrong.

If there is an option to run this in a debug mode or with a log creation i can do it and provide more feedback.

Thanks!

**Comment by metaphore** [comment]
What previous version did you use?
Could you please try out these commands in CMD and send stracktrace log back?
`java -jar gdx-texturepacker.jar -launcher awt`
`java -jar gdx-texturepacker.jar -launcher glsurface`

**Comment by rogerlopz** [comment]
To be honest i dont know what previous version i used but im sure it wasnt more than a year ago and it was with a different computer.

Running these commands i get the following results:
`
java -jar gdx-texturepacker.jar -launcher awt`
```
AWT launcher is starting
com.badlogic.gdx.utils.GdxRuntimeException: OpenGL is not supported by the video driver.
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.createDisplayPixelFormat(LwjglGraphics.java:322)
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:216)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.create(LwjglCanvas.java:192)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$1.addNotify(LwjglCanvas.java:92)
        at java.awt.Container.addNotify(Unknown Source)
        at javax.swing.JComponent.addNotify(Unknown Source)
        at java.awt.Container.addImpl(Unknown Source)
        at java.awt.Container.add(Unknown Source)
        at com.crashinvaders.texturepackergui.desktop.launchers.awt.MainFrame.<init>(MainFrame.java:81)
        at com.crashinvaders.texturepackergui.desktop.launchers.awt.AwtFrameLauncher$1.run(AwtFrameLauncher.java:40)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: org.lwjgl.LWJGLException: Pixel format not accelerated
        at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
        at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
        at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:253)
        at org.lwjgl.opengl.Display.createWindow(Display.java:306)
        at org.lwjgl.opengl.Display.create(Display.java:848)
        at org.lwjgl.opengl.Display.create(Display.java:757)
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.createDisplayPixelFormat(LwjglGraphics.java:314)
        ... 23 more
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at com.crashinvaders.texturepackergui.App.pause(App.java:191)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$4.run(LwjglCanvas.java:307)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```
`java -jar gdx-texturepacker.jar -launcher glsurface`
```
GL surface launcher is starting
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: OpenGL is not supported by the video driver.
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.createDisplayPixelFormat(LwjglGraphics.java:322)
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:216)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:144)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: org.lwjgl.LWJGLException: Pixel format not accelerated
        at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
        at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
        at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:253)
        at org.lwjgl.opengl.Display.createWindow(Display.java:306)
        at org.lwjgl.opengl.Display.create(Display.java:848)
        at org.lwjgl.opengl.Display.create(Display.java:757)
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.createDisplayPixelFormat(LwjglGraphics.java:314)
        ... 3 more
```
I can clearly see that the problem is because of OpenGL version on my integrated video card (intel hd 3000).

I have downloaded GPU Caps Viewer to see my opengl versión and i'm using is 3.1.0.
![opengl version](https://user-images.githubusercontent.com/4995589/32420881-f85cd990-c24e-11e7-8482-4b878fd17acf.png)

I guess my solution is to upgrade my computer or maybe switch to linux.

Thank you for your support!

**Comment by metaphore** [comment]
Yep, it's all up to OpenGL support on your end. But as this program claims, you should have it fully supported, it's weird. Do you have any problems running any other OpenGL based programs?

**Comment by rogerlopz** [comment]
Not that i know of, really.

**Comment by metaphore** [comment]
My only guess the tool shows an OpenGL version that can be supported by the hardware, but not actually by OS right now. Try to [update drivers](https://www.intel.com/content/www/us/en/support/detect.html), probably this will solve the issue. I'm afraid there is not much I can do, software works only on top of OpenGL so you need it to be supported.

PS: LibGDX can run in a software OpenGL mode, but I never had a chance to test it on a non GPU hardware. Try this command - `java -Dorg.lwjgl.opengl.Display.allowSoftwareOpenGL -jar gdx-texturepacker.jar`

**Comment by raeleus** [comment]
I think you have to change that command to:

`java -jar gdx-texturepacker.jar -Dorg.lwjgl.opengl.Display.allowSoftwareOpenGL=true`

I've been meaning to test something like this and I might have an old mac to try it on. I don't know if it will actually turn on, so no promises.

**Comment by rogerlopz** [comment]
Hi guys, i've run the command you guys send and im getting `Error: "-Dorg" is not a valid option`, am i missing something?

Also, i already had the latest version of my video card installed but it came from windows update. I'm now trying on the latest video driver provided by intel.

**Comment by raeleus** [comment]
Sorry guys, the Mac I have is too old to run any LibGDX games.

As for your issue, rogerlopz, I don't know how to reproduce that exact error message. Try `java -Dorg.lwjgl.opengl.Display.allowSoftwareOpenGL=true -jar gdx-texturepacker.jar`

**Comment by rogerlopz** [comment]
The commands i've run are:

First
`java -Dorg.lwjgl.opengl.Display.allowSoftwareOpenGL -jar gdx-texturepacker.jar`
output (translated from spanish):
> Error: The main class was not found or loaded .lwjgl.opengl.Display.allowSoftwareOpenGL 


Second
`java -jar gdx-texturepacker.jar -Dorg.lwjgl.opengl.Display.allowSoftwareOpenGL=true`
output:
> Error: "-Dorg" is not a valid option


Third
`java -Dorg.lwjgl.opengl.Display.allowSoftwareOpenGL=true -jar gdx-texturepacker.jar`
output (translated from spanish):
> Error: The main class was not found or loaded .lwjgl.opengl.Display.allowSoftwareOpenGL = true

To be honest, if this is really a bug im here to help but since this may be an old hardware problem i dont want you guys to waste resources on this when its me the one that should buy a new toaster.

**Comment by raeleus** [comment]
I have a personal interest in getting my own LibGDX apps to run on older hardware. So, it's not a waste of my time.

Anyway, are you running windows powershell or the command prompt? I get the same error as you in powershell, but it runs fine in cmd for some reason.

**Comment by rogerlopz** [comment]
You're right, i was using powershell, now with the CMD i get this:

Command: `java -Dorg.lwjgl.opengl.Display.allowSoftwareOpenGL=true -jar gdx-texturepacker.jar`
```
AWT launcher is starting
com.badlogic.gdx.utils.GdxRuntimeException: OpenGL 2.0 or higher with the FBO extension is required. OpenGL version: 1.1.0
Type: OpenGL
Version: 1:1:0
Vendor: Microsoft Corporation
Renderer: GDI Generic
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.initiateGLInstances(LwjglGraphics.java:347)
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.initiateGL(LwjglGraphics.java:226)
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:217)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.create(LwjglCanvas.java:192)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$1.addNotify(LwjglCanvas.java:92)
        at java.awt.Container.addNotify(Unknown Source)
        at javax.swing.JComponent.addNotify(Unknown Source)
        at java.awt.Container.addImpl(Unknown Source)
        at java.awt.Container.add(Unknown Source)
        at com.crashinvaders.texturepackergui.desktop.launchers.awt.MainFrame.<init>(MainFrame.java:81)
        at com.crashinvaders.texturepackergui.desktop.launchers.awt.AwtFrameLauncher$1.run(AwtFrameLauncher.java:40)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at com.crashinvaders.texturepackergui.App.pause(App.java:191)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$4.run(LwjglCanvas.java:307)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

Running this: `java -jar gdx-texturepacker.jar -Dorg.lwjgl.opengl.Display.allowSoftwareOpenGL=true`
I get this: Error: `"-Dorg.lwjgl.opengl.Display.allowSoftwareOpenGL=true" is not a valid option`

How can i truly see my OpenGL version?

**Comment by raeleus** [comment]
From my end it looks like it's not going to work. Perhaps Metaphore will have more insight.

See [this article](http://support.esri.com/en/technical-article/000011375) about getting the current OpenGL version. When I run it, it says my OpenGL version is 4.4. There is a drop down menu at the top to choose from the graphics renderers available.

**Comment by rogerlopz** [comment]
Im running OpenGL 3.1 after all.
![opengl](https://user-images.githubusercontent.com/4995589/32464785-6a02edbe-c2fe-11e7-8da6-d1aaaeccee02.png)

Better save some money haha

Thanks raelus and metaphore

**Comment by raeleus** [comment]
3.1 is supposed to work though. Internet sleuthing has led me to believe it's just a general Windows/Intel HD 3000/Java incompatibility: https://github.com/libgdx/libgdx/issues/4040

The suggestion is to roll back the Java version, which is a silly request in my opinion. Sorry!

**Comment by rogerlopz** [comment]
Hi raeleus.
I have installed the JDK 1.7 (update 80) and its working!
![its working](https://user-images.githubusercontent.com/4995589/32476557-4e0b1ffa-c335-11e7-8084-f06a08d7d7eb.png)

So i think you're right, its an incompatibily issue with my software/hardware.

Just to add more info, i have installed GDX Texture Packer GUI 4.5.0 and its running fine with or without the commands from above.
