### ISSUE TITLE
ExceptionInInitializerError on ubuntu 

### ISSUE THREAD

**Issue by arezaee** [crashinvaders/gdx-texture-packer-gui#40]
after run launcher.sh thrown with this exception
what 's wrong?

Version: 4.6.0
OS: Linux 4.15.0-20-generic amd64
JRE: 1.8.0_162 Oracle Corporation
External log file: /home/ali/.gdxtexturepackergui/logs/1804301224.log
Exception in thread "AWT-EventQueue-1" java.lang.ExceptionInInitializerError
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setVSync(LwjglGraphics.java:558)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.initialize(LwjglCanvas.java:125)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.<init>(LwjglCanvas.java:74)
	at com.crashinvaders.texturepackergui.desktop.launchers.awt.CustomLwjglCanvas.<init>(CustomLwjglCanvas.java:25)
	at com.crashinvaders.texturepackergui.desktop.launchers.awt.AwtFrameLauncher$1.run(AwtFrameLauncher.java:46)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.lwjgl.opengl.XRandR.findPrimary(XRandR.java:326)
	at org.lwjgl.opengl.XRandR.ScreentoDisplayMode(XRandR.java:315)
	at org.lwjgl.opengl.LinuxDisplay$3.run(LinuxDisplay.java:746)
	at org.lwjgl.opengl.LinuxDisplay$3.run(LinuxDisplay.java:743)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:743)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 20 more

**Comment by metaphore** [comment]
It looks like LWJGL cannot find any display configuration. Do you have OpenGL 2+ support? What GPU you are on? Try to run `gdx-texturepacker.jar` with `-launcher glsurface` or/and `-softopengl`, see if there is any difference.

**Comment by metaphore** [comment]
Looks like a local configuration issue. If anyone will experience the same problem, feel free to reopen this one.
