### ISSUE TITLE
[Crash Report] 

### ISSUE THREAD

**Issue by rising-force** [crashinvaders/gdx-texture-packer-gui#43]
<details><summary>Stack trace</summary>

```
com.github.czyzby.lml.util.LmlParsingException: Error occurred during parsing near line 47 of the original file: "main.lml" during parsing template part: "'import' macro result" on line: 9 of its content. Template part is most likely an evaluated macro or argument result, extracted from the original template.
REASON: Container widget can manage only one child.
	Due implementation of the parser, the real problematic line might SLIGHTLY vary from the given line number(s), but exception message should be clear enough to find the actual error.
	Currently parsed template part:
6 |VALID|     <vistable background="paneLockBg" touchable="enabled" visible="true" pad="16">
7 |VALID|         <image style="custom/logo16-bw" size="72" hexcolor="ffffff40"/>
8 |VALID|     </vistable>
9 |ERROR| </shrinkcontainer>

	This template part was most likely evaluated during parsing this original template part (if a macro or an argument ends on this line, its content most likely causes the error): 
44 |VALID|                 <container growy="false" fill="true">
45 |VALID|                     <:titledpane id="titledPaneGlobalSettings" title="@panelTitleGlobalSettings" icon="custom/ic-title-global-settings">
46 |VALID|                         <:import path="lml/paneGlobalSettings.lml"/>
47 |ERROR|                     </:titledpane>
48 |     |                 </container>
49 |     | 
50 |     |                 <container growy="true" fill="true">

	If this is not enough to determine the error, call AbstractLmlParser#setLinesAmountPrintedOnException(int) with a suitable number. If you keep a lot of nested macros and want to see the whole invocation tree, try debugging through parsing and use getTemplateReader().toString() before exception occurs to check all current parsed template layers.
	Note that this exception would not have been thrown if the parser was not strict.
	at com.github.czyzby.lml.parser.impl.AbstractLmlParser.throwErrorIfStrict(AbstractLmlParser.java:887)
	at com.github.czyzby.lml.parser.impl.AbstractLmlParser.throwErrorIfStrict(AbstractLmlParser.java:880)
	at com.github.czyzby.lml.parser.impl.tag.actor.ContainerLmlTag.addChild(ContainerLmlTag.java:38)
	at com.github.czyzby.lml.parser.impl.tag.actor.ContainerLmlTag.handleValidChild(ContainerLmlTag.java:31)
	at com.github.czyzby.lml.parser.impl.tag.AbstractActorLmlTag.handleChild(AbstractActorLmlTag.java:251)
	at com.github.czyzby.lml.parser.impl.DefaultLmlParser.processClosedTag(DefaultLmlParser.java:379)
	at com.github.czyzby.lml.parser.impl.DefaultLmlParser.processTagEntity(DefaultLmlParser.java:323)
	at com.github.czyzby.lml.parser.impl.DefaultLmlParser.processTag(DefaultLmlParser.java:308)
	at com.github.czyzby.lml.parser.impl.DefaultLmlParser.parse(DefaultLmlParser.java:139)
	at com.github.czyzby.lml.parser.impl.DefaultLmlParser.parseTemplate(DefaultLmlParser.java:100)
	at com.github.czyzby.lml.parser.impl.AbstractLmlParser.parseTemplate(AbstractLmlParser.java:197)
	at com.github.czyzby.lml.parser.impl.AbstractLmlParser.createView(AbstractLmlParser.java:232)
	at com.github.czyzby.autumn.mvc.component.ui.controller.impl.AnnotatedViewController.createView(AnnotatedViewController.java:76)
	at com.github.czyzby.autumn.mvc.component.ui.InterfaceService.initiateView(InterfaceService.java:212)
	at com.github.czyzby.autumn.mvc.component.ui.InterfaceService.access$600(InterfaceService.java:63)
	at com.github.czyzby.autumn.mvc.component.ui.InterfaceService$ScreenSwitchingRunnable.run(InterfaceService.java:647)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.executeRunnables(LwjglCanvas.java:265)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:231)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

</details>

**Comment by metaphore** [comment]
@rising-force thanks for the report.
Could you please describe any steps to reproduce it? Do you receive this on application startup?

**Comment by metaphore** [comment]
I can't reproduce the crash. If anyone will get any new information on this one, feel free to reopen the issue.
