### ISSUE TITLE
Create 9patch from png failed

### ISSUE THREAD

**Issue by Naxos84** [crashinvaders/gdx-texture-packer-gui#44]
Steps to reproduce:

- Start gdx texture packer
- Load png file
- right-click loaded file
- select 9patch
- exception occurs

Apparently I can't use the built in reporting  cause I get a URI to long error.

**Comment by metaphore** [comment]
Yeah, reporting has a content limitation, sometimes it's too long when you put extra comments and I'm still in a process of solving it. But you can actually use it to extract stacktrace, because without it, I'm afraid, it's not possible to reproduce the issue. Also you can grab the log from `~/.gdxtexturepacker/logs`, I would appreciate if you attach one. Thanks!

**Comment by Naxos84** [comment]
I managed to extract and convert the created string (thanks so search & replace) 🗡 
Hope this helps.
<details><summary>Stack trace</summary>

```
com.badlogic.gdx.utils.GdxRuntimeException: Unable to invoke method: com.badlogic.gdx.utils.reflect.Method@7ba05e9f of object: com.crashinvaders.texturepackergui.controllers.main.inputfiles.InputFilePropertiesDialogController@20a4cab0
	at com.github.czyzby.lml.parser.impl.action.MethodActorConsumer.consume(MethodActorConsumer.java:41)
	at com.github.czyzby.lml.parser.impl.attribute.OnChangeLmlAttribute$1.changed(OnChangeLmlAttribute.java:29)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:182)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:147)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:124)
	at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:92)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:59)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:351)
	at com.crashinvaders.common.PrioritizedInputMultiplexer$Wrapper.touchUp(PrioritizedInputMultiplexer.java:133)
	at com.crashinvaders.common.PrioritizedInputMultiplexer.touchUp(PrioritizedInputMultiplexer.java:80)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:332)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:238)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.badlogic.gdx.utils.reflect.ReflectionException: Exception occurred in method: onNinePatchChecked
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:114)
	at com.github.czyzby.kiwi.util.gdx.reflection.Reflection.invokeMethod(Reflection.java:130)
	at com.github.czyzby.lml.parser.impl.action.MethodActorConsumer.consume(MethodActorConsumer.java:38)
	... 27 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:108)
	... 29 more
Caused by: com.github.czyzby.lml.util.LmlParsingException: Error occurred during parsing near line 19 of the original file: "dialogNinePatchEditor.lml".
REASON: Unable to parse passed template due to an unexpected exception.
	Due implementation of the parser, the real problematic line might SLIGHTLY vary from the given line number(s), but exception message should be clear enough to find the actual error.
	Currently parsed template part:
16 |VALID|                 <container clip="true" fill="true" grow="true">
17 |VALID|                     <stack>
18 |VALID|                         <image tiled="custom/transparent-light"/>
19 |ERROR|                         <:actor id="compositionHolder" method="createCompositionHolder"/>
20 |     |                     </stack>
21 |     |                 </container>
22 |     |                 <table onecolumn="true" growx="true" padtop="4">

	If this is not enough to determine the error, call AbstractLmlParser#setLinesAmountPrintedOnException(int) with a suitable number. If you keep a lot of nested macros and want to see the whole invocation tree, try debugging through parsing and use getTemplateReader().toString() before exception occurs to check all current parsed template layers.
	at com.github.czyzby.lml.parser.impl.AbstractLmlParser.throwError(AbstractLmlParser.java:875)
	at com.github.czyzby.lml.parser.impl.DefaultLmlParser.parseTemplate(DefaultLmlParser.java:106)
	at com.github.czyzby.lml.parser.impl.AbstractLmlParser.parseTemplate(AbstractLmlParser.java:197)
	at com.github.czyzby.lml.parser.impl.AbstractLmlParser.createView(AbstractLmlParser.java:232)
	at com.github.czyzby.autumn.mvc.component.ui.controller.impl.AnnotatedViewDialogController.prepareDialogInstance(AnnotatedViewDialogController.java:89)
	at com.github.czyzby.autumn.mvc.component.ui.controller.impl.AnnotatedViewDialogController.show(AnnotatedViewDialogController.java:46)
	at com.github.czyzby.autumn.mvc.component.ui.InterfaceService.showDialog(InterfaceService.java:316)
	at com.crashinvaders.texturepackergui.controllers.main.inputfiles.InputFilePropertiesDialogController.navigateToNinePatchEditor(InputFilePropertiesDialogController.java:193)
	at com.crashinvaders.texturepackergui.controllers.main.inputfiles.InputFilePropertiesDialogController.onNinePatchChecked(InputFilePropertiesDialogController.java:155)
	... 34 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unable to invoke method: com.badlogic.gdx.utils.reflect.Method@5bc92b68 of object: com.crashinvaders.texturepackergui.controllers.ninepatcheditor.NinePatchEditorDialog@1f3e073f
	at com.github.czyzby.lml.parser.impl.action.MethodActorConsumer.consume(MethodActorConsumer.java:41)
	at com.github.czyzby.lml.parser.impl.tag.macro.EvaluateLmlMacroTag.executeMethod(EvaluateLmlMacroTag.java:99)
	at com.github.czyzby.lml.parser.impl.tag.macro.EvaluateLmlMacroTag.closeTag(EvaluateLmlMacroTag.java:77)
	at com.github.czyzby.lml.parser.impl.DefaultLmlParser.processMacro(DefaultLmlParser.java:396)
	at com.github.czyzby.lml.parser.impl.DefaultLmlParser.processTagEntity(DefaultLmlParser.java:328)
	at com.github.czyzby.lml.parser.impl.DefaultLmlParser.processTag(DefaultLmlParser.java:308)
	at com.github.czyzby.lml.parser.impl.DefaultLmlParser.parse(DefaultLmlParser.java:139)
	at com.github.czyzby.lml.parser.impl.DefaultLmlParser.parseTemplate(DefaultLmlParser.java:100)
	... 41 more
Caused by: com.badlogic.gdx.utils.reflect.ReflectionException: Exception occurred in method: createCompositionHolder
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:114)
	at com.github.czyzby.kiwi.util.gdx.reflection.Reflection.invokeMethod(Reflection.java:130)
	at com.github.czyzby.lml.parser.impl.action.MethodActorConsumer.consume(MethodActorConsumer.java:38)
	... 48 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:108)
	... 50 more
Caused by: java.lang.ClassCastException: com.badlogic.gdx.scenes.scene2d.utils.NinePatchDrawable cannot be cast to com.badlogic.gdx.scenes.scene2d.utils.TextureRegionDrawable
	at com.crashinvaders.texturepackergui.controllers.ninepatcheditor.ContentGrid.<init>(ContentGrid.java:15)
	at com.crashinvaders.texturepackergui.controllers.ninepatcheditor.CompositionHolder.<init>(CompositionHolder.java:49)
	at com.crashinvaders.texturepackergui.controllers.ninepatcheditor.NinePatchEditorDialog.createCompositionHolder(NinePatchEditorDialog.java:152)
	... 55 more
```

</details>

**Comment by metaphore** [comment]
Thanks a lot, that helped. Patched version should be out this week.
