### ISSUE TITLE
[Report] no error but crash.

### ISSUE THREAD

**Issue by nerondes** [crashinvaders/gdx-texture-packer-gui#57]
Log is empty. The error report screen opens directly when we run.

<details><summary>Application log</summary>

```

```

</details>

**Comment by metaphore** [comment]
Is it started to happen recently after you installed new version? What OS and app version? Monday, 24 September 2018, 03:20AM +10:00 from nerondes  notifications@github.com :

**Comment by nerondes** [comment]
4.73 v. (last version)
Windows 10 Pro 
vers. 1803 
comp. 17134.285

**Comment by metaphore** [comment]
Hmm, strange though. I would appreciate if you could run the program from the console and copypaste the output, there should be something on crash I believe. To do it `cd` to an installation folder (usually `C:\Program Files (x86)\GdxTexturePacker` and run from CMD `java -jar gdx-texturepacker.jar`. 
Thanks in advance!

**Comment by nerondes** [comment]
I got this log when I ran it from the console.
***********************************************************************
Version: 4.7.3
OS: Windows 10 10.0 amd64
JRE: 1.8.0_181 Oracle Corporation
External log file: C:\Users\.......\.gdxtexturepackergui\logs\1809240403.log
com.badlogic.gdx.utils.GdxRuntimeException: OpenGL is not supported by the video driver.
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.createDisplayPixelFormat(LwjglGraphics.java:355)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:249)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.create(LwjglCanvas.java:192)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$1.addNotify(LwjglCanvas.java:92)
	at java.awt.Container.addNotify(Unknown Source)
	at javax.swing.JComponent.addNotify(Unknown Source)
	at java.awt.Container.addNotify(Unknown Source)
	at javax.swing.JComponent.addNotify(Unknown Source)
	at java.awt.Container.addNotify(Unknown Source)
	at javax.swing.JComponent.addNotify(Unknown Source)
	at java.awt.Container.addNotify(Unknown Source)
	at javax.swing.JComponent.addNotify(Unknown Source)
	at javax.swing.JRootPane.addNotify(Unknown Source)
	at java.awt.Container.addNotify(Unknown Source)
	at java.awt.Window.addNotify(Unknown Source)
	at java.awt.Frame.addNotify(Unknown Source)
	at java.awt.Window.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at com.crashinvaders.texturepackergui.desktop.launchers.awt.AwtFrameLauncher$1.run(AwtFrameLauncher.java:50)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:253)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.createDisplayPixelFormat(LwjglGraphics.java:347)
	... 34 more
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.crashinvaders.texturepackergui.App.pause(App.java:167)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$4.run(LwjglCanvas.java:307)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by metaphore** [comment]
Yes, unfortunately.  There has been a couple more reports regarding Intel HD 3000 issues, so it's a common problem.
