### ISSUE TITLE
[Crash Report] Crashing on startup

### ISSUE THREAD

**Issue by KennethMurugu** [crashinvaders/gdx-texture-packer-gui#60]
The app  crashes immedaitely on startup and displays the "Error Report" window. It seems to only happen when I'm connected to the internet. When offline, the application opens normally.

<details><summary>Stack trace</summary>

```
com.github.czyzby.lml.util.LmlParsingException: Error occurred during parsing near line 0 of the original file: "null" during parsing template part: "null" on line: 0 of its content. Template part is most likely an evaluated macro or argument result, extracted from the original template.
REASON: Unable to parse passed template due to an unexpected exception.
	Due implementation of the parser, the real problematic line might SLIGHTLY vary from the given line number(s), but exception message should be clear enough to find the actual error.
	Currently parsed template part:

	This template part was most likely evaluated during parsing this original template part (if a macro or an argument ends on this line, its content most likely causes the error): 

	If this is not enough to determine the error, call AbstractLmlParser#setLinesAmountPrintedOnException(int) with a suitable number. If you keep a lot of nested macros and want to see the whole invocation tree, try debugging through parsing and use getTemplateReader().toString() before exception occurs to check all current parsed template layers.
	at com.github.czyzby.lml.parser.impl.AbstractLmlParser.throwError(AbstractLmlParser.java:875)
	at com.github.czyzby.lml.parser.impl.DefaultLmlParser.parseTemplate(DefaultLmlParser.java:106)
	at com.github.czyzby.lml.parser.impl.AbstractLmlParser.parseTemplate(AbstractLmlParser.java:197)
	at com.github.czyzby.lml.parser.impl.AbstractLmlParser.createView(AbstractLmlParser.java:232)
	at com.github.czyzby.autumn.mvc.component.ui.controller.impl.AnnotatedViewController.createView(AnnotatedViewController.java:76)
	at com.github.czyzby.autumn.mvc.component.ui.InterfaceService.initiateView(InterfaceService.java:212)
	at com.github.czyzby.autumn.mvc.component.ui.InterfaceService.access$600(InterfaceService.java:63)
	at com.github.czyzby.autumn.mvc.component.ui.InterfaceService$ScreenSwitchingRunnable.run(InterfaceService.java:647)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.executeRunnables(LwjglCanvas.java:265)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:231)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.github.czyzby.lml.parser.impl.DefaultLmlParser.processRegularTag(DefaultLmlParser.java:537)
	at com.github.czyzby.lml.parser.impl.DefaultLmlParser.processTagEntity(DefaultLmlParser.java:333)
	at com.github.czyzby.lml.parser.impl.DefaultLmlParser.processTag(DefaultLmlParser.java:308)
	at com.github.czyzby.lml.parser.impl.DefaultLmlParser.parse(DefaultLmlParser.java:139)
	at com.github.czyzby.lml.parser.impl.DefaultLmlParser.parseTemplate(DefaultLmlParser.java:100)
	... 22 more
```

</details>

**Comment by metaphore** [comment]
Yeah, the bug has already been fixed. The thing is this is a "new version accessable" notification causes that crash, which means that you have to go to https://github.com/crashinvaders/gdx-texture-packer-gui/releases and manually download the latest version.

**Comment by KennethMurugu** [comment]
Ah, thank you.
