### ISSUE TITLE
[Mac] Getting JRELoadError on launch

### ISSUE THREAD

**Issue by prime31** [crashinvaders/gdx-texture-packer-gui#66]
Using JRE:

```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

Running the jar directly with `java -jar ../Java/desktop.jar` does seem to work.

**Comment by metaphore** [comment]
Could you please attach a stack trace?

**Comment by prime31** [comment]
When I run `JavaAppLauncher` from the command line I dont get a strack trace. No logs at all. Double-clicking the .app dumps this to Console.app:

```
default	00:58:30.428176 -0800	Finder	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 1159 vs 2224, 512, <private>
default	00:58:30.429179 -0800	NowPlayingTouchUI	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 328 vs 1158, 512, <private>
default	00:58:30.430698 -0800	universalaccessd	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 0 vs 326, 513, <private>
default	00:58:30.431554 -0800	Console	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 1152 vs 1154, 513, <private>
default	00:58:30.431889 -0800	contextstored	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 107 vs 1155, 513, <private>
default	00:58:30.433316 -0800	WindowServer	SetFrontProcessInternal(0x0,0x12012 pid316) Posting kCGSEventResume to application, allWindows=0 noWindows=0 userGenerated=0.
default	00:58:30.437203 -0800	NowPlayingTouchUI	[NowPlayingTouchUI] Reloading available apps due to workspace activating an application: NSConcreteNotification 0x600001fe8780 {name = NSWorkspaceDidActivateApplicationNotification; object = <NSWorkspace: 0x6000013cc2e0>; userInfo = {
    NSWorkspaceApplicationKey = "<NSRunningApplication: 0x6000023c7600 (com.apple.finder - 316)>";
}}
default	00:58:30.465317 -0800	bird	<private> setEnabledTopics <private> ignoredTopics <private> opportunisticTopics <private> sendToDaemon: YES
default	00:58:30.465339 -0800	bird	<private> setting delegate <private>
default	00:58:30.465353 -0800	bird	<private> setEnabledTopics <private> ignoredTopics <private> opportunisticTopics <private> sendToDaemon: YES
default	00:58:30.465492 -0800	bird	<private> Delivering queued delegate calls: 0
default	00:58:30.465525 -0800	bird	<private> _setEnableStatusNotifications NO sendToDaemon YES
default	00:58:30.474843 -0800	bird	<private> setEnabledTopics <private> ignoredTopics <private> opportunisticTopics <private> sendToDaemon: YES
default	00:58:30.474862 -0800	bird	<private> setting delegate <private>
default	00:58:30.474876 -0800	bird	<private> setEnabledTopics <private> ignoredTopics <private> opportunisticTopics <private> sendToDaemon: YES
default	00:58:30.475006 -0800	bird	<private> Delivering queued delegate calls: 0
default	00:58:30.475032 -0800	bird	<private> _setEnableStatusNotifications NO sendToDaemon YES
default	00:58:30.546532 -0800	NowPlayingTouchUI	[NowPlayingTouchUI] Updating now playing apps with 0 added and 0 removed.
default	00:58:30.546568 -0800	NowPlayingTouchUI	[NowPlayingTouchUI] Reloading control strip presence because of now playing apps reload.
error	00:58:30.582327 -0800	Finder	Unable to load Info.plist exceptions (eGPUOverrides)
error	00:58:30.592898 -0800	taskgated	cannot open file at line 42263 of [95fbac39ba]
error	00:58:30.592969 -0800	taskgated	os_unix.c:42263: (2) open(/var/db/DetachedSignatures) - No such file or directory
default	00:58:30.593269 -0800	taskgated	MacOS error: -67062
default	00:58:30.596096 -0800	Dock	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 0 vs 659, 256, <private>
default	00:58:30.596421 -0800	CommCenter	#I handleLSNotitifcation_sync: Application launched: <private>
default	00:58:30.596533 -0800	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] | enter
default	00:58:30.597109 -0800	loginwindow	-[PersistentAppsSupport applicationLaunched:] | enter. clearing logout in progress and last logout time
default	00:58:30.597139 -0800	loginwindow	-[PersistentAppsSupport applicationReady:] | App: GDX Texture Packer, ready, updating active tracking timer
default	00:58:30.597155 -0800	loginwindow	-[PersistentAppsSupport(Internal) updateActiveTrackingTimer] | Creating timer
default	00:58:30.597198 -0800	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : GDX Texture Packer
default	00:58:30.608391 -0800	mds	directQueryFetchResultsReply 32769 1795162112 35
default	00:58:30.607929 -0800	lsd	UNIX error exception: 8
default	00:58:30.608831 -0800	mds	directQueryFetchResultsReply 32770 1795162112 35
error	00:58:30.611352 -0800	lsd	cannot open file at line 42263 of [95fbac39ba]
error	00:58:30.611376 -0800	lsd	os_unix.c:42263: (2) open(/var/db/DetachedSignatures) - No such file or directory
default	00:58:30.648312 -0800	tccd	PID[227] is checking access for target PID[13008]
error	00:58:30.649269 -0800	tccd	cannot open file at line 42263 of [95fbac39ba]
error	00:58:30.649294 -0800	tccd	os_unix.c:42263: (2) open(/var/db/DetachedSignatures) - No such file or directory
default	00:58:30.649704 -0800	tccd	MacOS error: -67062
default	00:58:30.658336 -0800	launchservicesd	UNIX error exception: 22
error	00:58:30.659911 -0800	launchservicesd	cannot open file at line 42263 of [95fbac39ba]
error	00:58:30.659936 -0800	launchservicesd	os_unix.c:42263: (2) open(/var/db/DetachedSignatures) - No such file or directory
default	00:58:30.660113 -0800	launchservicesd	MacOS error: -67062
default	00:58:30.662651 -0800	launchservicesd	CHECKIN:0x0-0x26d26d 13008 com.crashinvaders.texturepackergui.desktop.ApplicationStarter
default	00:58:30.663030 -0800	loginwindow	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 1279 vs 1807, 257, <private>
default	00:58:30.663336 -0800	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] | enter
default	00:58:30.663796 -0800	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : GDX Texture Packer
error	00:58:30.670205 -0800	JavaAppLauncher	Unable to load Info.plist exceptions (eGPUOverrides)
default	00:58:30.670738 -0800	CommCenter	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 1153 vs 2161, 512, <private>
default	00:58:30.671869 -0800	2BUA8C4S2C.com.agilebits.onepassword-osx-helper	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 0 vs 327, 512, <private>
default	00:58:30.671623 -0800	nsurlsessiond	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 100 vs 846, 512, <private>
``

**Comment by itsabhiaryan** [comment]
When I'm using` java -jar gdx-texturepacker.jar` on Mac machine 

I'm getting below log on terminal with black screen.

```
AWT launcher is starting
Version: 4.8.2
OS: Mac OS X 10.15.3 x86_64
JRE: 12.0.2 Oracle Corporation
External log file: /Users/itsabhiaryan/.gdxtexturepackergui/logs/2003080108.log
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/Users/itsabhiaryan/Downloads/gdx-texturepacker-4/gdx-texturepacker.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[ExtensionModuleRepositoryService] Cached data was loaded
[ConfigurationController] Incremental fonts are disabled
[GlobalShortcutHandler] Parsing shortcut file: hotkeys_default.txt
```

**Comment by phanviet** [comment]
I'm meeting the same issue, who resolved it? pls help.

**Comment by metaphore** [comment]
This issue is related to some old LWJGL code used in the app and it happens on the JRE version 12 and newer. This will likely be fixed in the next release, but for now as a workaround you can downgrade installed Java to 8 or 11.

**Comment by phanviet** [comment]
I'm using java 11 but still black screen on Mac OS
```
java -jar desktop.jar

AWT launcher is starting
Version: 4.8.2
OS: Mac OS X 10.15.6 x86_64
JRE: 11.0.8 Oracle Corporation
External log file: /Users/xxx/.gdxtexturepackergui/logs/2010060200.log
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/Applications/GDX%20Texture%20Packer.app/Contents/Java/desktop.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[ExtensionModuleRepositoryService] Cached data is outdated.
[ExtensionModuleRepositoryService] Requesting new data from remote server.
[ConfigurationController] Incremental fonts are disabled
[GlobalShortcutHandler] Parsing shortcut file: hotkeys_default.txt
[ExtensionModuleRepositoryService] Data was loaded from remote server.
```

**Comment by metaphore** [comment]
@phanviet Interesting, however, there's no actual exception in the log. Could you please try this command 
`-java -jar desktop.jar -XstartOnFirstThread`?

**Comment by phanviet** [comment]
@metaphore 
```
java -jar desktop.jar -XstartOnFirstThread
Error: "-XstartOnFirstThread" is not a valid option
```

**Comment by metaphore** [comment]
@phanviet Sorry I don't have MacOS by hand to test. Might be just the param order. Try this one, please.
```
java -XstartOnFirstThread -jar desktop.jar
```

**Comment by phanviet** [comment]
Thanks, here is my log:
```
(venv) venv ❯ java -XstartOnFirstThread -jar desktop.jar
AWT launcher is starting
Version: 4.8.2
OS: Mac OS X 10.15.6 x86_64
JRE: 11.0.8 Oracle Corporation
External log file: /Users/vietphan/.gdxtexturepackergui/logs/2010080915.log
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/Applications/GDX%20Texture%20Packer.app/Contents/Java/desktop.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```
And the application window didn't show.

**Comment by metaphore** [comment]
Ok, things might be really twisted and it's difficult to tell why in that case.
I'm currently porting the app launcher from LWJGL2 to LWJGL3 and several important issues should be fixed in there.
It's still "work in progress", but if it will run for you, I guess the next release will be the remedy.

@phanviet I'd appreciate it if you could try to run this build using the same `java -XstartOnFirstThread -jar gdx-texturepacker-201008.jar` command.

https://www.dropbox.com/s/fb0cmjky3h9dc8v/gdx-texturepacker-201008.jar?dl=0

**Comment by phanviet** [comment]
Thanks for your kind @metaphore , pls help take a look:
```
> java -XstartOnFirstThread -jar gdx-texturepacker-201008.jar
External log file: /Users/xxx/.gdxtexturepackergui/logs/2010080944.log
Version: 4.8.2
OS: Mac OS X 10.15.6 x86_64
JRE: 11.0.8 Oracle Corporation

```
and it's hang.

I tried another:
```
> java -jar gdx-texturepacker-201008.jar
External log file: /Users/xxx/.gdxtexturepackergui/logs/2010080946.log
Version: 4.8.2
OS: Mac OS X 10.15.6 x86_64
JRE: 11.0.8 Oracle Corporation
2020-10-08 21:46:39.019 java[2890:33413] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff2f665b57 __exceptionPreprocess + 250
        1   libobjc.A.dylib                     0x00007fff684ac5bf objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff2f68e34c -[NSException raise] + 9
        3   AppKit                              0x00007fff2c8885ec -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 310
        4   AppKit                              0x00007fff2c870052 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1416
        5   AppKit                              0x00007fff2c86fac3 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
        6   libglfw.dylib                       0x000000012d825bc9 libglfw.dylib + 68553
        7   libglfw.dylib                       0x000000012d81f416 libglfw.dylib + 42006
        8   ???                                 0x0000000119783950 0x0 + 4722276688
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1]    2890 abort      java -jar gdx-texturepacker-201008.jar
```
then crash

**Comment by metaphore** [comment]
Thanks for checking out!
So the second one is quite obvious, that's why we need that `-XstartOnFirstThread` parameter.

But the fact it doesn't show the window is really weird. I'm gonna get it tested on macos this weekend and will see if I could reproduce it.

In meantime, there's still a chance that it's a common bug, and totally unrelated to the system configuration. One thing to try is to clean to the "data" folder to make a cold start. Basically just delete (backup everything from there if needed first) this for and give it another try.
`/Users/xxx/.gdxtexturepackergui`

**Comment by phanviet** [comment]
There are no good news when I try delete data and re-run. Hope you can reproduce this bug and resolve it, thanks.

**Comment by metaphore** [comment]
The [4.9.0](https://github.com/crashinvaders/gdx-texture-packer-gui/releases/tag/4.9.0) was recently released and there might be some possible fixed for the issue. @phanviet I'd appreciate it if you could give it a try. Thanks!

**Comment by phanviet** [comment]
Thanks for your hard work @metaphore .
I just tried and have no lucky, my step:
1. Remove dir: `/Users/xxx/.gdxtexturepackergui`
2. Run: `java -jar desktop.jar`, and log is below:
```
(venv) venv ❯ java -jar desktop.jar
Restarting the JVM with "startOnFirstThread" parameter.
External log file: /Users/xxx/.gdxtexturepackergui/logs/2011130906.log
Version: 4.9.0
OS: Mac OS X 10.15.6 x86_64
JRE: 11.0.8 Oracle Corporation
GPU: Intel(R) Iris(TM) Plus Graphics 640
OpenGL vendor: Intel Inc.
OpenGL version: 2.1 INTEL-14.7.8
[ExtensionModuleRepositoryService] Cached data is outdated.
[ExtensionModuleRepositoryService] Requesting new data from remote server.
[ConfigurationController] Incremental fonts are disabled
[GlobalShortcutHandler] Parsing shortcut file: hotkeys_default.txt
com.badlogic.gdx.utils.GdxRuntimeException: Unable to invoke method: setupInitialProject of type: com.crashinvaders.texturepackergui.controllers.ConfigurationController@4263b080 with parameters: [com.crashinvaders.texturepackergui.controllers.model.ModelService@62d363ab, com.crashinvaders.texturepackergui.controllers.projectserializer.ProjectSerializer@7889a1ac]
	at com.github.czyzby.autumn.context.impl.method.MethodInvocation.invoke(MethodInvocation.java:50)
	at com.github.czyzby.autumn.processor.impl.InitiateAnnotationProcessor.doAfterScanning(InitiateAnnotationProcessor.java:42)
	at com.github.czyzby.autumn.context.ContextInitializer.invokeProcessorActionsAfterInitiation(ContextInitializer.java:351)
	at com.github.czyzby.autumn.context.ContextInitializer.initiate(ContextInitializer.java:294)
	at com.crashinvaders.texturepackergui.App.initiateContext(App.java:100)
	at com.crashinvaders.texturepackergui.App.create(App.java:85)
	at com.crashinvaders.texturepackergui.desktop.ApplicationListenerWrapper.create(ApplicationListenerWrapper.java:14)
	at com.crashinvaders.texturepackergui.desktop.Lwjgl3AppWrapper.create(Lwjgl3AppWrapper.java:41)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:433)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:381)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:138)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:114)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.start(ApplicationStarter.java:56)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:35)
Caused by: com.badlogic.gdx.utils.reflect.ReflectionException: Exception occurred in method: setupInitialProject
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:114)
	at com.github.czyzby.kiwi.util.gdx.reflection.Reflection.invokeMethod(Reflection.java:130)
	at com.github.czyzby.autumn.context.impl.method.MethodInvocation.invoke(MethodInvocation.java:47)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:108)
	... 15 more
Caused by: java.lang.NullPointerException
	at com.crashinvaders.texturepackergui.controllers.projectserializer.ProjectSerializer.loadProject(ProjectSerializer.java:72)
	at com.crashinvaders.texturepackergui.controllers.ConfigurationController.setupInitialProject(ConfigurationController.java:267)
	... 20 more
```
And it's hang, app window doesn't appear.

**Comment by metaphore** [comment]
Thanks a lot @phanviet 
At least in this version there are some nice logs with the clear crash stack trace. I think I found what's the problem in your case and it's gonna be patched up in the upcoming release!
