### ISSUE TITLE
Crashes when started through launcher.bat

### ISSUE THREAD

**Issue by Grisgram** [crashinvaders/gdx-texture-packer-gui#79]
I hope the stacktrace helps
cheers!

Version: 4.8.2
OS: Windows 10 10.0 amd64
JRE: 14 Oracle Corporation

[GlobalShortcutHandler] Parsing shortcut file: hotkeys_default.txt
com.badlogic.gdx.utils.GdxRuntimeException: Unable to invoke method: initiateFirstScreen of type: com.github.czyzby.autumn.mvc.component.ui.InterfaceService@686ca2d8 with parameters: []
	at com.github.czyzby.autumn.context.impl.method.MethodInvocation.invoke(MethodInvocation.java:50)
	at com.github.czyzby.autumn.processor.impl.InitiateAnnotationProcessor.doAfterScanning(InitiateAnnotationProcessor.java:42)
	at com.github.czyzby.autumn.context.ContextInitializer.invokeProcessorActionsAfterInitiation(ContextInitializer.java:351)
	at com.github.czyzby.autumn.context.ContextInitializer.initiate(ContextInitializer.java:294)
	at com.crashinvaders.texturepackergui.App.initiateContext(App.java:100)
	at com.crashinvaders.texturepackergui.App.create(App.java:85)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.create(LwjglCanvas.java:210)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$1.addNotify(LwjglCanvas.java:100)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/javax.swing.JRootPane.addNotify(JRootPane.java:729)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/java.awt.Window.addNotify(Window.java:778)
	at java.desktop/java.awt.Frame.addNotify(Frame.java:490)
	at java.desktop/java.awt.Window.show(Window.java:1040)
	at java.desktop/java.awt.Component.show(Component.java:1717)
	at java.desktop/java.awt.Component.setVisible(Component.java:1664)
	at java.desktop/java.awt.Window.setVisible(Window.java:1023)
	at com.crashinvaders.texturepackergui.desktop.launchers.awt.AwtFrameLauncher$1.run(AwtFrameLauncher.java:50)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: com.badlogic.gdx.utils.reflect.ReflectionException: Exception occurred in method: initiateFirstScreen
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:114)
	at com.github.czyzby.kiwi.util.gdx.reflection.Reflection.invokeMethod(Reflection.java:130)
	at com.github.czyzby.autumn.context.impl.method.MethodInvocation.invoke(MethodInvocation.java:47)
	... 37 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:108)
	... 39 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: At least one view has to be set as first.
	at com.github.czyzby.autumn.mvc.component.ui.InterfaceService.initiateFirstScreen(InterfaceService.java:199)
	... 44 more

**Comment by Grisgram** [comment]
hi - any news on this? could you reproduce?

**Comment by pavel-malin** [comment]
Hi, help me plz
version 4.8.2
Ubuntu 20.04 amd64
java 13

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/home/malinroot/%d0%97%d0%b0%d0%b3%d1%80%d1%83%d0%b7%d0%ba%d0%b8/gdx-texturepacker/gdx-texture-packer-gui/distribution/files/gdx-texturepacker.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
AL lib: alsa_open_playback: Could not open playback device 'default': Нет такого файла или каталога
org.lwjgl.LWJGLException: Could not locate OpenAL library.
	at org.lwjgl.openal.AL.create(AL.java:151)
	at org.lwjgl.openal.AL.create(AL.java:102)
	at org.lwjgl.openal.AL.create(AL.java:201)
	at com.badlogic.gdx.backends.openal.OpenALAudio.<init>(OpenALAudio.java:69)
	at com.badlogic.gdx.backends.openal.OpenALAudio.<init>(OpenALAudio.java:54)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.<init>(LwjglCanvas.java:101)
	at aurelienribon.texturepackergui.Main$1.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!

**Comment by metaphore** [comment]
Seems like a relative issue to https://github.com/crashinvaders/gdx-texture-packer-gui/issues/75
Please follow the other thread regarding this. For now, a quick fix is to run the app on an older JRE (7/8).

**Comment by metaphore** [comment]
The issue was fixed in the 4.9.0 release. Feel free to reopen if the problem persists.
