### ISSUE TITLE
Crash on startup. No default view controller found.

### ISSUE THREAD

**Issue by Grisgram** [crashinvaders/gdx-texture-packer-gui#92]
> Please paste the crash log in here (already in your clipboard) and, if possible, provide any information that may help to reproduce the issue.

Hi - just tried to start the 4.9 using win-launcher

<details><summary>Application Log</summary>

```
Version: 4.9.0
OS: Windows 10 10.0 amd64
JRE: 1.8.0_242-release JetBrains s.r.o
GPU: Intel(R) UHD Graphics 630
OpenGL vendor: Intel
OpenGL version: 4.5.0 - Build 25.20.100.6617
[GlobalShortcutHandler] Parsing shortcut file: hotkeys_default.txt
com.badlogic.gdx.utils.GdxRuntimeException: Unable to invoke method: initiateFirstScreen of type: com.github.czyzby.autumn.mvc.component.ui.InterfaceService@233795b6 with parameters: []
	at com.github.czyzby.autumn.context.impl.method.MethodInvocation.invoke(MethodInvocation.java:50)
	at com.github.czyzby.autumn.processor.impl.InitiateAnnotationProcessor.doAfterScanning(InitiateAnnotationProcessor.java:42)
	at com.github.czyzby.autumn.context.ContextInitializer.invokeProcessorActionsAfterInitiation(ContextInitializer.java:351)
	at com.github.czyzby.autumn.context.ContextInitializer.initiate(ContextInitializer.java:294)
	at com.crashinvaders.texturepackergui.App.initiateContext(App.java:100)
	at com.crashinvaders.texturepackergui.App.create(App.java:85)
	at com.crashinvaders.texturepackergui.desktop.ApplicationListenerWrapper.create(ApplicationListenerWrapper.java:14)
	at com.crashinvaders.texturepackergui.desktop.Lwjgl3AppWrapper.create(Lwjgl3AppWrapper.java:41)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:433)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:381)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:138)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:114)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.start(ApplicationStarter.java:56)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:35)
Caused by: com.badlogic.gdx.utils.reflect.ReflectionException: Exception occurred in method: initiateFirstScreen
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:114)
	at com.github.czyzby.kiwi.util.gdx.reflection.Reflection.invokeMethod(Reflection.java:130)
	at com.github.czyzby.autumn.context.impl.method.MethodInvocation.invoke(MethodInvocation.java:47)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:108)
	... 15 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: At least one view has to be set as first.
	at com.github.czyzby.autumn.mvc.component.ui.InterfaceService.initiateFirstScreen(InterfaceService.java:199)
	... 20 more
```
</details>

**Comment by metaphore** [comment]
Hi @Grisgram, thanks for the report.

Looking at the log, it's hard to tell what happened. Has it started to crash since the update to `4.9.0`? 

I'm not sure if it will be a quick fix, but in the meantime, just to get it going, you may try to reset the app's data to see if the clean run works. Just delete the `%USERPROFILE%\.gdxtexturepackergui` dir (make a backup) and try to start the app.

Please let me know if it helps.

**Comment by Grisgram** [comment]
Hi thanks for looking into it.
I deleted the folder, double-clicked the win launcher batch file, ... and it crashed - sorry that I don't have better news

what can I do to help you track it down?


<details><summary>Application Log</summary>

```
Version: 4.9.0
OS: Windows 10 10.0 amd64
JRE: 1.8.0_242-release JetBrains s.r.o
GPU: Intel(R) UHD Graphics 630
OpenGL vendor: Intel
OpenGL version: 4.5.0 - Build 25.20.100.6617
[GlobalShortcutHandler] Parsing shortcut file: hotkeys_default.txt
com.badlogic.gdx.utils.GdxRuntimeException: Unable to invoke method: initiateFirstScreen of type: com.github.czyzby.autumn.mvc.component.ui.InterfaceService@233795b6 with parameters: []
	at com.github.czyzby.autumn.context.impl.method.MethodInvocation.invoke(MethodInvocation.java:50)
	at com.github.czyzby.autumn.processor.impl.InitiateAnnotationProcessor.doAfterScanning(InitiateAnnotationProcessor.java:42)
	at com.github.czyzby.autumn.context.ContextInitializer.invokeProcessorActionsAfterInitiation(ContextInitializer.java:351)
	at com.github.czyzby.autumn.context.ContextInitializer.initiate(ContextInitializer.java:294)
	at com.crashinvaders.texturepackergui.App.initiateContext(App.java:100)
	at com.crashinvaders.texturepackergui.App.create(App.java:85)
	at com.crashinvaders.texturepackergui.desktop.ApplicationListenerWrapper.create(ApplicationListenerWrapper.java:14)
	at com.crashinvaders.texturepackergui.desktop.Lwjgl3AppWrapper.create(Lwjgl3AppWrapper.java:41)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:433)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:381)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:138)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:114)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.start(ApplicationStarter.java:56)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:35)
Caused by: com.badlogic.gdx.utils.reflect.ReflectionException: Exception occurred in method: initiateFirstScreen
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:114)
	at com.github.czyzby.kiwi.util.gdx.reflection.Reflection.invokeMethod(Reflection.java:130)
	at com.github.czyzby.autumn.context.impl.method.MethodInvocation.invoke(MethodInvocation.java:47)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:108)
	... 15 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: At least one view has to be set as first.
	at com.github.czyzby.autumn.mvc.component.ui.InterfaceService.initiateFirstScreen(InterfaceService.java:199)
	... 20 more
```
</details>

**Comment by metaphore** [comment]
No worries, I didn't expect it to be that easy haha.
But was it working for you before the update (any previous version)?

**Comment by Grisgram** [comment]
I had a problem about half a year ago (I don't know which version was current at that time, sorry) when I started development on my latest game and it was about jdk14 I used but i couldn't step back to jdk 8 for several reasons so I started writing command scripts for packr to get going.

Now I found that you released a new version and my other issue has been closed with the comment "fixed in 4.9", so I gave it another try.
not fixed :-)

**Comment by metaphore** [comment]
Yeah, that's right, for this release the recent versions of JRE are recommended over the old ones. And I'm not sure these two issues have any relation thought. But judging by the logs, you're not using Java 14.
> JRE: 1.8.0_242-release JetBrains s.r.o


If that's not a big deal I'd give it a try with JRE 11 or 14 to see if there's any difference.

**Comment by Grisgram** [comment]
My bad! I sent the log from the second try (where i tried with v8) - sorry for the confusion

Here is the from 14:

<details><summary>Application Log</summary>

```
Version: 4.9.0
OS: Windows 10 10.0 amd64
JRE: 14 Oracle Corporation
GPU: Intel(R) UHD Graphics 630
OpenGL vendor: Intel
OpenGL version: 4.5.0 - Build 25.20.100.6617
[GlobalShortcutHandler] Parsing shortcut file: hotkeys_default.txt
com.badlogic.gdx.utils.GdxRuntimeException: Unable to invoke method: initiateFirstScreen of type: com.github.czyzby.autumn.mvc.component.ui.InterfaceService@7ae42ce3 with parameters: []
	at com.github.czyzby.autumn.context.impl.method.MethodInvocation.invoke(MethodInvocation.java:50)
	at com.github.czyzby.autumn.processor.impl.InitiateAnnotationProcessor.doAfterScanning(InitiateAnnotationProcessor.java:42)
	at com.github.czyzby.autumn.context.ContextInitializer.invokeProcessorActionsAfterInitiation(ContextInitializer.java:351)
	at com.github.czyzby.autumn.context.ContextInitializer.initiate(ContextInitializer.java:294)
	at com.crashinvaders.texturepackergui.App.initiateContext(App.java:100)
	at com.crashinvaders.texturepackergui.App.create(App.java:85)
	at com.crashinvaders.texturepackergui.desktop.ApplicationListenerWrapper.create(ApplicationListenerWrapper.java:14)
	at com.crashinvaders.texturepackergui.desktop.Lwjgl3AppWrapper.create(Lwjgl3AppWrapper.java:41)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:433)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:381)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:138)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:114)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.start(ApplicationStarter.java:56)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:35)
Caused by: com.badlogic.gdx.utils.reflect.ReflectionException: Exception occurred in method: initiateFirstScreen
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:114)
	at com.github.czyzby.kiwi.util.gdx.reflection.Reflection.invokeMethod(Reflection.java:130)
	at com.github.czyzby.autumn.context.impl.method.MethodInvocation.invoke(MethodInvocation.java:47)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:108)
	... 15 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: At least one view has to be set as first.
	at com.github.czyzby.autumn.mvc.component.ui.InterfaceService.initiateFirstScreen(InterfaceService.java:199)
	... 20 more
```
</details>

**Comment by metaphore** [comment]
Hey @Grisgram could you please check if this bug is present in the latest release ([4.10.0](https://github.com/crashinvaders/gdx-texture-packer-gui/releases/tag/4.10.0))? Cheers

**Comment by Grisgram** [comment]
Unfortunately yes... :-/

Version: 4.10.0
OS: Windows 10 10.0 amd64
JRE: 14 Oracle Corporation
GPU: Intel(R) UHD Graphics 630
OpenGL vendor: Intel
OpenGL version: 4.5.0 - Build 25.20.100.6617
[GlobalShortcutHandler] Parsing shortcut file: hotkeys_default.txt
com.badlogic.gdx.utils.GdxRuntimeException: Unable to invoke method: initiateFirstScreen of type: com.github.czyzby.autumn.mvc.component.ui.InterfaceService@49b2a47d with parameters: []
	at com.github.czyzby.autumn.context.impl.method.MethodInvocation.invoke(MethodInvocation.java:50)
	at com.github.czyzby.autumn.processor.impl.InitiateAnnotationProcessor.doAfterScanning(InitiateAnnotationProcessor.java:42)
	at com.github.czyzby.autumn.context.ContextInitializer.invokeProcessorActionsAfterInitiation(ContextInitializer.java:351)
	at com.github.czyzby.autumn.context.ContextInitializer.initiate(ContextInitializer.java:294)
	at com.crashinvaders.texturepackergui.App.initiateContext(App.java:100)
	at com.crashinvaders.texturepackergui.App.create(App.java:85)
	at com.crashinvaders.texturepackergui.desktop.ApplicationListenerWrapper.create(ApplicationListenerWrapper.java:14)
	at com.crashinvaders.texturepackergui.desktop.Lwjgl3AppWrapper.create(Lwjgl3AppWrapper.java:42)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:433)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:381)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:141)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.start(ApplicationStarter.java:56)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:35)
Caused by: com.badlogic.gdx.utils.reflect.ReflectionException: Exception occurred in method: initiateFirstScreen
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:114)
	at com.github.czyzby.kiwi.util.gdx.reflection.Reflection.invokeMethod(Reflection.java:130)
	at com.github.czyzby.autumn.context.impl.method.MethodInvocation.invoke(MethodInvocation.java:47)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:108)
	... 15 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: At least one view has to be set as first.
	at com.github.czyzby.autumn.mvc.component.ui.InterfaceService.initiateFirstScreen(InterfaceService.java:199)
	... 20 more

**Comment by metaphore** [comment]
Ok, thanks @Grisgram 
I will keep looking for a way to reproduce it on my end

**Comment by Grisgram** [comment]
Thanks for trying :)
If I find the time in the next couple of days I might create a fork and try it from Android Studio or intelliJ on my end - maybe I can help you out.

I know there are kinds of bugs or strange behaviors that can make you crazy :-)

**Comment by Grisgram** [comment]
I have new information:
Created a fork of the repo, created a desktop configuration... and it starts (from within intelliJ)!

So it must be some kind of:
- error in the cmd script (jars/paths/whatever)
- something that got downloaded while opening the project (any missing module, external resource, whatever)

I am currently working on tracking that down

**Comment by Grisgram** [comment]
no success on my side so far... it keeps crashing when run through java.exe but works in the IDE...

**Comment by metaphore** [comment]
Thanks a lot for looking into it @Grisgram 
IntelliJ Idea uses a bundled JRE it comes with to run Java projects.
So it could be some rare combination of your system JRE + batch script params.

Could you please try to run the distribution JAR from CMD without any extra commands
```
java -jar gdx-texturepacker.jar
```

**Comment by Grisgram** [comment]
Same error, here is what I also tried:
by default my system seams to point to some java 8 installation i can not find on my machine - so I guess it's the jre from Android Studio
interesting is also that the GPU is the intel onboard graphics and not the geforce2070 of my system - is that normal?

JAVA_HOME is not set in my system, so java.exe must've been found through the path

So I looked into the path and found the android studio jre.
I added another path to my openJDK 14 BEFORE the android studio one... and then jdk 14 was used

but both java.exe versions (jre from studio and openjdk 14) crash with the same error.
my openjdk installation is not modified at all... downloaded, unpacked,.. done.

Version: 4.10.0
OS: Windows 10 10.0 amd64
JRE: 1.8.0_242-release JetBrains s.r.o
GPU: Intel(R) UHD Graphics 630
OpenGL vendor: Intel
OpenGL version: 4.5.0 - Build 25.20.100.6617
com.badlogic.gdx.utils.GdxRuntimeException: Unable to invoke method: initiateFirstScreen of type: com.github.czyzby.autumn.mvc.component.ui.InterfaceService@20bd8be5 with parameters: []
        at com.github.czyzby.autumn.context.impl.method.MethodInvocation.invoke(MethodInvocation.java:50)
        at com.github.czyzby.autumn.processor.impl.InitiateAnnotationProcessor.doAfterScanning(InitiateAnnotationProcessor.java:42)
        at com.github.czyzby.autumn.context.ContextInitializer.invokeProcessorActionsAfterInitiation(ContextInitializer.java:351)
        at com.github.czyzby.autumn.context.ContextInitializer.initiate(ContextInitializer.java:294)
        at com.crashinvaders.texturepackergui.App.initiateContext(App.java:100)
        at com.crashinvaders.texturepackergui.App.create(App.java:85)
        at com.crashinvaders.texturepackergui.desktop.ApplicationListenerWrapper.create(ApplicationListenerWrapper.java:14)
        at com.crashinvaders.texturepackergui.desktop.Lwjgl3AppWrapper.create(Lwjgl3AppWrapper.java:42)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:433)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:381)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:141)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
        at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.start(ApplicationStarter.java:56)
        at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:35)

**Comment by metaphore** [comment]
There was another report with a very similar log  #124
I can see that the JRE is exactly the same in both reports - **1.8.0_242-release JetBrains s.r.o**
Could be a bug in this specific release. 

@Grisgram can I ask you to try the app with some other JRE and post the log if it crashes please?
