### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by snehuh** [crashinvaders/gdx-texture-packer-gui#96]
I'm very new to this so I am unable to identify the problem

Version: 4.9.0
OS: Windows 10 10.0 amd64
JRE: 15.0.1 Oracle Corporation
GPU: Intel(R) Iris(R) Plus Graphics
OpenGL vendor: Intel
OpenGL version: 4.6.0 - Build 26.20.100.7641
com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoClassDefFoundError: com/github/czyzby/lml/parser/impl/tag/builder/TextLmlActorBuilder
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:120)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.start(ApplicationStarter.java:56)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:35)
Caused by: java.lang.NoClassDefFoundError: com/github/czyzby/lml/parser/impl/tag/builder/TextLmlActorBuilder
	at com.github.czyzby.lml.parser.impl.attribute.building.TextLmlAttribute.getBuilderType(TextLmlAttribute.java:15)
	at com.github.czyzby.lml.parser.impl.EmptyLmlSyntax.addBuildingAttributeProcessor(EmptyLmlSyntax.java:271)
	at com.github.czyzby.lml.parser.impl.DefaultLmlSyntax.registerBuildingAttributes(DefaultLmlSyntax.java:412)
	at com.github.czyzby.lml.parser.impl.DefaultLmlSyntax.registerAttributes(DefaultLmlSyntax.java:374)
	at com.github.czyzby.lml.parser.impl.DefaultLmlSyntax.<init>(DefaultLmlSyntax.java:270)
	at com.github.czyzby.lml.parser.impl.DefaultLmlParser.<init>(DefaultLmlParser.java:32)
	at com.github.czyzby.lml.util.LmlParserBuilder.getInstanceOfParser(LmlParserBuilder.java:49)
	at com.github.czyzby.lml.util.LmlParserBuilder.<init>(LmlParserBuilder.java:43)
	at com.github.czyzby.lml.util.LmlParserBuilder.<init>(LmlParserBuilder.java:36)
	at com.github.czyzby.lml.util.Lml.parser(Lml.java:62)
	at com.github.czyzby.autumn.mvc.component.ui.InterfaceService.<init>(InterfaceService.java:100)
	at com.crashinvaders.texturepackergui.App.addDefaultComponents(App.java:117)
	at com.crashinvaders.texturepackergui.App.initiateContext(App.java:98)
	at com.crashinvaders.texturepackergui.App.create(App.java:85)
	at com.crashinvaders.texturepackergui.desktop.ApplicationListenerWrapper.create(ApplicationListenerWrapper.java:14)
	at com.crashinvaders.texturepackergui.desktop.Lwjgl3AppWrapper.create(Lwjgl3AppWrapper.java:41)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:433)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:381)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:138)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:114)
	... 2 more
Caused by: java.lang.ClassNotFoundException: com.github.czyzby.lml.parser.impl.tag.builder.TextLmlActorBuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 22 more

**Comment by snehuh** [comment]
Problem solved upon uninstalling and reinstalling it

**Comment by metaphore** [comment]
Looks pretty odd, almost like the application executable is damaged. Please let me know if something similar will come up again.
