### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Ajax12Ajax** [crashinvaders/gdx-texture-packer-gui#97]
<details><summary>Application Log</summary>

```
Version: 4.10.0
OS: Windows 10 10.0 amd64
JRE: 1.8.0_271 Oracle Corporation
GPU: GeForce GTX 1050 Ti/PCIe/SSE2
OpenGL vendor: NVIDIA Corporation
OpenGL version: 4.6.0 NVIDIA 461.09
[ExtensionModuleRepositoryService] Cached data was loaded
[ConfigurationController] Incremental fonts are disabled
[VisUI] Warning, using invalid libGDX version for VisUI 1.4.8.
You are using libGDX 1.9.11 but you need 1.9.12. This may cause unexpected problems and runtime exceptions.
[GlobalShortcutHandler] Parsing shortcut file: hotkeys_default.txt
Output directory doesn't exist. Creating: "C:\Users\janst\Documents\libGDXproject\connectThePoints\android\assets\images"
Packing is started
WARNING: Input file doesn't exist: "C:/Users/janst/Documents/Dysk Google/connection/texture/images/gameTexture/field-red.png"
WARNING: Input file doesn't exist: "C:/Users/janst/Documents/Dysk Google/connection/texture/images/gameTexture/field-blue.png"
WARNING: Input file doesn't exist: "C:/Users/janst/Documents/Dysk Google/connection/texture/images/gameTexture/field-green.png"
WARNING: Input file doesn't exist: "C:/Users/janst/Documents/Dysk Google/connection/texture/images/gameTexture/field-purple.png"
WARNING: Input file doesn't exist: "C:/Users/janst/Documents/Dysk Google/connection/texture/images/gameTexture/field-dn.png"
WARNING: Input file doesn't exist: "C:/Users/janst/Documents/Dysk Google/connection/texture/images/gameTexture/background.png"
WARNING: Input file doesn't exist: "C:/Users/janst/Documents/Dysk Google/connection/texture/images/gameTexture/field-gray.png"
[text-red]Exception occurred:[] No images to pack
[text-red]Stack trace:[] 
java.lang.IllegalStateException: No images to pack
	at com.crashinvaders.texturepackergui.controllers.packing.processors.PackingProcessor.performPacking(PackingProcessor.java:49)
	at com.crashinvaders.texturepackergui.controllers.packing.processors.PackingProcessor.processPackage(PackingProcessor.java:40)
	at com.crashinvaders.texturepackergui.utils.packprocessing.CompositePackProcessor.processPackage(CompositePackProcessor.java:20)
	at com.crashinvaders.texturepackergui.utils.packprocessing.PackProcessingManager.lambda$execute$0(PackProcessingManager.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Packing is started
Packing.....................................................................
............
Writing 1253x816: C:\Users\janst\Documents\libGDXproject\connectThePoints\android\assets\images\menuTexture.png
Packing is done
Total pack files size is 71571 bytes
1 pages
Total processing time: 2.24sec

Packing is started
Packing.................................................
Writing 812x804: C:\Users\janst\Documents\libGDXproject\connectThePoints\android\assets\images\gameTexture.png
Packing is done
Total pack files size is 314076 bytes
1 pages
Total processing time: 1.95sec

[text-red]Exception occurred:[] Output directory is not specified
[text-red]Stack trace:[] 
java.lang.IllegalStateException: Output directory is not specified
	at com.crashinvaders.texturepackergui.controllers.packing.processors.DataValidationProcessor.processPackage(DataValidationProcessor.java:22)
	at com.crashinvaders.texturepackergui.utils.packprocessing.CompositePackProcessor.processPackage(CompositePackProcessor.java:20)
	at com.crashinvaders.texturepackergui.utils.packprocessing.PackProcessingManager.lambda$execute$0(PackProcessingManager.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[text-red]Exception occurred:[] Output directory is not specified
[text-red]Stack trace:[] 
java.lang.IllegalStateException: Output directory is not specified
	at com.crashinvaders.texturepackergui.controllers.packing.processors.DataValidationProcessor.processPackage(DataValidationProcessor.java:22)
	at com.crashinvaders.texturepackergui.utils.packprocessing.CompositePackProcessor.processPackage(CompositePackProcessor.java:20)
	at com.crashinvaders.texturepackergui.utils.packprocessing.PackProcessingManager.lambda$execute$0(PackProcessingManager.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[text-red]Exception occurred:[] Output directory is not specified
[text-red]Stack trace:[] 
java.lang.IllegalStateException: Output directory is not specified
	at com.crashinvaders.texturepackergui.controllers.packing.processors.DataValidationProcessor.processPackage(DataValidationProcessor.java:22)
	at com.crashinvaders.texturepackergui.utils.packprocessing.CompositePackProcessor.processPackage(CompositePackProcessor.java:20)
	at com.crashinvaders.texturepackergui.utils.packprocessing.PackProcessingManager.lambda$execute$0(PackProcessingManager.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

java.lang.RuntimeException: Actor: VisImageButton
|  Image: select-down
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:125)
	at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:93)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.crashinvaders.common.PrioritizedInputMultiplexer$Wrapper.touchUp(PrioritizedInputMultiplexer.java:136)
	at com.crashinvaders.common.PrioritizedInputMultiplexer.touchUp(PrioritizedInputMultiplexer.java:83)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:87)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:187)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:394)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:141)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.start(ApplicationStarter.java:56)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:35)
Caused by: java.lang.IllegalArgumentException: actor cannot be null.
	at com.badlogic.gdx.scenes.scene2d.ui.Table.getCell(Table.java:417)
	at com.kotcrab.vis.ui.widget.MenuItem.getImageCell(MenuItem.java:352)
	at com.kotcrab.vis.ui.widget.file.internal.AbstractSuggestionPopup.createMenuItem(AbstractSuggestionPopup.java:36)
	at com.kotcrab.vis.ui.widget.file.internal.DirsSuggestionPopup.createRecentDirSuggestions(DirsSuggestionPopup.java:137)
	at com.kotcrab.vis.ui.widget.file.internal.DirsSuggestionPopup.showRecentDirectories(DirsSuggestionPopup.java:121)
	at com.kotcrab.vis.ui.widget.file.FileChooser$6.changed(FileChooser.java:352)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
	... 15 more
```
</details>

**Comment by metaphore** [comment]
Hi there,
I see it from the log that it crashed possibly from clicking a menu item? Could you please tell what happened?
